export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ONE_USER = 'GET_ONE_USER';

export const ADD_NEW_SECTION = 'ADD_NEW_SECTION';
export const CHANGE_SHOW_VIEW = 'CHANGE_SHOW_VIEW';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const ARE_INPUTS_VALID = 'ARE_INPUTS_VALID';
export const VALID_INPUT = 'VALID_INPUT';
export const GET_ALL_SECTIONS = 'GET_ALL_SECTIONS'

export const GET_FULL_ARTICLE = 'GET_FULL_ARTICLE';
export const GET_COMMENTS_FROM_ARTICLE = 'GET_COMMENTS_FROM_ARTICLE';
export const GET_ALL_ARTICLES = 'GET_ALL_ARTICLES'

export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS';
